### ISSUE TITLE
Enable client URLs without any assumed suffixes (e.g. /client or /client/api)

### ISSUE THREAD

**Issue by yadvr** [Autonomiccs/apache-cloudstack-java-client#26]
All, can you please help do a 1.0.4 release that includes PR #25 work and would allow usage of the library with an upcoming plugin for CloudStack (out-of-band management plugin for nested-CloudStack environments). /cc @rafaelweingartner 

Thanks,
Rohit

**Comment by rafaelweingartner** [comment]
Would not you like to add the client timeout in this next version as well?

**Comment by yadvr** [comment]
@rafaelweingartner I would prefer to have such an option, let me see if I'm able to find time to send a PR today. Otherwise, for my use-case PR#25 is much needed.

**Comment by yadvr** [comment]
@rafaelweingartner okay I've sent a new PR that will adds a mechanism to override/specify a custom connection timeout, please review -- https://github.com/Autonomiccs/apache-cloudstack-java-client/pull/27
If you're happy with the change, please merge this and do a 1.0.4 release. Thanks!

**Comment by rafaelweingartner** [comment]
Sure, I only had a comment on PR #27 
Also, I will edit this issue to reflect the changes on these new PRs you created.
The release process is automatically executed by Jenkins, and the release notes is also generated automatically from PRs and issues closed.
