### ISSUE TITLE
How to use it "Map of (key/value pairs)"

### ISSUE THREAD

**Issue by 492162921** [Autonomiccs/apache-cloudstack-java-client#35]
http://cloudstack.apache.org/api/apidocs-4.10/apis/addGuestOs.html 
How the "details" parameter is called ? 

Please reply in time. Thank you.

**Comment by rafaelweingartner** [comment]
Looking at the code, Apache CloudStack is expecting a Map of Maps. For further details on how to create these data objects you can refer to users@cloudstack.apache.org

**Comment by rafaelweingartner** [comment]
I am closing this one as it is not related to the use of our library per se, but regarding CloudStack's API.
