### ISSUE TITLE
Please provide object model for response types

### ISSUE THREAD

**Issue by ccaspanello** [Autonomiccs/apache-cloudstack-java-client#36]
The executeRequest method accepts a type and the GSON parser is used under the covers to create that object.  It would be useful if this library came packaged with the object model to make the response object oriented.
ie,
client.executeRequest( request, ListUsersResponse.class );

**Comment by rafaelweingartner** [comment]
I am not sure I follow. Something like this address your needs?
 https://github.com/Autonomiccs/apache-cloudstack-java-client/blob/5c4f129cdea3bc5ef90dd0d8e0605be2e72d8741/src/main/java/br/com/autonomiccs/apacheCloudStack/client/ApacheCloudStackClient.java#L538

**Comment by ccaspanello** [comment]
Yes, that is the API I am using.  It would be nice if this API could provide the POJO classes for easy use. ie,

```
@Data
public class ListUsersResponse {

  @SerializedName( "listusersresponse" )
  private ListUsers listUsers;

}

@Data
public class ListUsers {

  private int count;

  @SerializedName( "user" )
  private List<User> users;

}

@Data
public class User {

  private String id;
  private String username;
  private String firstname;
  private String lastname;
  private String email;
  private String created;
  private String state;
  private String account;
  private String roleid;
  private String roletype;
  private String rolename;
  private String domainid;
  private String domain;
  private String apikey;
  private String accountid;
  private int accounttype;
  // Missing some properties I do not care about
}
```

**Comment by ccaspanello** [comment]
`@Data` is a Lombok annotation so I didn't have to manually write out the constructor / getters / setters.
https://projectlombok.org/features/Data

**Comment by rafaelweingartner** [comment]
I see what you mean now. Well, if you are willing to open a PR and propose these classes. I would be happy to review and get it merged. Otherwise, we would need to wait until somebody else proposes these classes.

**Comment by ccaspanello** [comment]
Sure, I will see if I can spend some time to create a PR mid week.

**Comment by ccaspanello** [comment]
So after digging in; I think it may be better to use the CloudStack API model instead.

https://github.com/apache/cloudstack/tree/master/api/src/main/java/org/apache/cloudstack/api/command/user/affinitygroup
